#!/bin/bash

NAME="taikonetwork_app"                           # Name of application
DJANGODIR=/webapps/taiko_django/taikonetwork      # Django project directory
SOCKFILE=/webapps/taiko_django/run/gunicorn.sock  # Unix socket for communication
USER=taiko                                        # User to run app
GROUP=webapps                                     # Groups to run app
NUM_WORKERS=3                                     # Number worker processes
DJANGO_SETTINGS_MODULE=taikonetwork.settings      # Django settings file to use
DJANGO_WSGI_MODULE=taikonetwork.wsgi              # WSGI module name

echo "Starting $NAME as 'whoami'..."

# Activate the virtual environment
cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it does not exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start Gunicorn
# Note: Programs meant to run under supervisor should not daemonize themselves
#         (Do not use --daemon)
exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE